package manabu.enomerator;

public enum UserState {
   SHARE_CONTACT,
   SHARE_LOCATION,
   REGISTERED,
   MAIN_MENU,
   SELL_MENU,
   CRUD_MENU,
   CHOSING_ONE_CAR,
   RECEIVING_CARPHOT0,
   SENDCARPHOTO,
   RECIVINGPHOTCOMMAND,

   RECIVINGPHOTOFORCURRENTCAR,
   CREATECAR,
   UPDATE_CAR,
   FULL_UPDATE,
   DELETE;

}
